export type PrecipitationName =
  | "Blizzard"
  | "Cinder Storm"
  | "Cloudy"
  | "Fog"
  | "Hail"
  | "Heat Lightning"
  | "Heavy Rain"
  | "Heavy Snow"
  | "Light Rain"
  | "Light Snow"
  | "Partly Cloudy"
  | "Rain"
  | "Rainbow"
  | "Sleet"
  | "Snow"
  | "Sun Shower"
  | "Sunny"
  | "Thundersnow"
  | "Thunderstorm";
